"""add reviews table

Revision ID: 6633b921fb60
Revises: bb791e53134b
Create Date: 2026-08-08 17:03:50.805249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6633b921fb60'
down_revision = 'bb791e53134b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('external_review_id', sa.Text(), nullable=True),
    sa.Column('reviewer_name', sa.Text(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('rating_raw', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('recommended', sa.Boolean(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('review_url', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.Date(), nullable=True),
    sa.Column('match_method', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'source_id', 'external_review_id', name='uq_reviews_entity_source_external')
    )
    op.create_index('ix_reviews_entity', 'reviews', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_entity', table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
