"""initial schema

Revision ID: bb791e53134b
Revises: 
Create Date: 2026-08-08 15:59:08.854807

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb791e53134b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.Text(), nullable=False),
    sa.Column('triggered_by', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dietary_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('festivals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('official_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('merge_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('canonical_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.Text(), nullable=True),
    sa.Column('candidate_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('resolution_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('crawl_delay_sec', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('booths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('region_theme', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location_description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('festival_id', 'slug', name='uq_booths_festival_slug')
    )
    op.create_table('concert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('series', sa.Text(), nullable=False),
    sa.Column('artist_name', sa.Text(), nullable=False),
    sa.Column('performance_date', sa.Date(), nullable=False),
    sa.Column('venue', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('page_kind', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_unchanged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['raw_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_pages_source_hash', 'raw_pages', ['source_id', 'content_hash'], unique=False)
    op.create_index('ix_raw_pages_url', 'raw_pages', ['url'], unique=False)
    op.create_table('seminars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('seminar_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('presenter_names', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('venue', sa.Text(), nullable=True),
    sa.Column('price_usd', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('requires_reservation', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concert_showtimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concert_event_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['concert_event_id'], ['concert_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_page_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extractor_version', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('natural_key_hint', sa.Text(), nullable=True),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['raw_page_id'], ['raw_pages.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['extracted_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_extracted_entity_key', 'extracted_records', ['entity_type', 'natural_key_hint'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booth_id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booth_id'], ['booths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canonical_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('canonical_id', sa.Integer(), nullable=False),
    sa.Column('extracted_record_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('match_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('match_method', sa.Text(), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extracted_record_id'], ['extracted_records.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extracted_record_id')
    )
    op.create_index('ix_canonical_links_entity', 'canonical_links', ['entity_type', 'canonical_id'], unique=False)
    op.create_table('entity_field_provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('canonical_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('extracted_record_id', sa.Integer(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['extracted_record_id'], ['extracted_records.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'canonical_id', 'field_name', 'source_id', 'extracted_record_id', name='uq_field_prov_candidate')
    )
    op.create_index('ix_field_prov_entity', 'entity_field_provenance', ['entity_type', 'canonical_id', 'field_name'], unique=False)
    op.create_table('menu_item_dietary_tags',
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('dietary_tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dietary_tag_id'], ['dietary_tags.id'], ),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('menu_item_id', 'dietary_tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_item_dietary_tags')
    op.drop_index('ix_field_prov_entity', table_name='entity_field_provenance')
    op.drop_table('entity_field_provenance')
    op.drop_index('ix_canonical_links_entity', table_name='canonical_links')
    op.drop_table('canonical_links')
    op.drop_table('menu_items')
    op.drop_index('ix_extracted_entity_key', table_name='extracted_records')
    op.drop_table('extracted_records')
    op.drop_table('concert_showtimes')
    op.drop_table('seminars')
    op.drop_index('ix_raw_pages_url', table_name='raw_pages')
    op.drop_index('ix_raw_pages_source_hash', table_name='raw_pages')
    op.drop_table('raw_pages')
    op.drop_table('concert_events')
    op.drop_table('booths')
    op.drop_table('sources')
    op.drop_table('merge_conflicts')
    op.drop_table('festivals')
    op.drop_table('dietary_tags')
    op.drop_table('crawl_runs')
    # ### end Alembic commands ###
